# Generated by Django 2.2 on 2019-05-24 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='completed_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
