# Generated by Django 2.1.5 on 2019-04-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='TodoItem_models_py',
        ),
    ]
